FROM node:18-alpine AS build

WORKDIR /usr/src/app

RUN npm install -g @angular/cli

COPY package.json package-lock.json ./

RUN mkdir -p node_modules
RUN npm ci
COPY . .

RUN mkdir -p dist
RUN mkdir -p dist/reseaux-revolution

RUN ng build --configuration production


FROM nginx:latest

COPY --from=build /usr/src/app/dist/reseaux-revolution /var/www/app

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]